version: "3.4"
services:

  
  crawler:
    build: ./shop_products
    network_mode: service:openvpn-client
    depends_on:
      - openvpn-client
    volumes:
      - products:/usr/src/app/shop_products/data

  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_CONFIG_FILE=config.ovpn
    volumes:
      - /home/vbauer/Mega/Projects/BillaProducts/vpn:/data/vpn
    restart: unless-stopped

volumes:
  products:
