version: "3.4"
services:

  crawler:
    build: ./crawler
    network_mode: service:openvpn-client
    depends_on:
      - openvpn-client
    volumes:
      - /home/vbauer/crawler/data:/crawler/data
    environment:
      - PRODUCTS_BILLA_DB=/crawler/data/products_billa.sqlite3

  openvpn-client:
    build: ./vpn
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_CONFIG_FILE=config.ovpn
    restart: unless-stopped
