version: "3.4"
services:

  crawler:
    build: ./crawler
    network_mode: service:openvpn-client
    depends_on:
      - openvpn-client
    volumes:
      - crawler_downloads:/usr/src/crawler/downloads

  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_CONFIG_FILE=config.ovpn
    volumes:
      - /home/vbauer/Mega/Projects/shop_products/crawl-infra/vpn:/data/vpn
    restart: unless-stopped

volumes:
  crawler_downloads:
